Repository GIL-DONG-MU/ddu-ru-backend, pull requests merged in 2025-08, with the labels that each got.

#30 deploy: 도커화 및 CI workflow 작성
  .dockerignore
  .env.prod
  .github/workflows/ci.yml
  .gitignore
  Dockerfile
  README.Docker.md
  README.md
  build.gradle
  deploy.sh
  docker-compose.override.yml
  docker-compose.yml
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
Labels: BE, 🌐 deploy

#35 fix: CI 워크플로우 수정
  .env.prod
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/ci.yml
  README.Docker.md
  README.md
  deploy.sh
  docker-compose.override.yml
  docker-compose.yml
  src/main/resources/data.sql
Labels: 🐛 bug, BE

#39 Hotfix#37 dodcker command change
  deploy.sh
  docker-compose.yml
Labels: BE, 🌐 deploy, ❗️HOTFIX

#40 feat: CI workflow test
  .env.prod
  .github/workflows/ci.yml
Labels: BE, 🌐 deploy

#42 feat: 소셜로그인 모바일 확장
  build.gradle
  src/main/java/com/dduru/gildongmu/auth/controller/OauthController.java
  src/main/java/com/dduru/gildongmu/auth/dto/google/PersonExtendedInfo.java
  src/main/java/com/dduru/gildongmu/auth/enums/AgeRange.java
  src/main/java/com/dduru/gildongmu/auth/enums/Gender.java
  src/main/java/com/dduru/gildongmu/auth/service/AbstractOauthService.java
  src/main/java/com/dduru/gildongmu/auth/service/GoogleLoginService.java
  src/main/java/com/dduru/gildongmu/auth/service/KakaoLoginService.java
  src/main/java/com/dduru/gildongmu/auth/service/OauthAuthService.java
  src/main/java/com/dduru/gildongmu/auth/service/OauthService.java
  src/main/java/com/dduru/gildongmu/auth/utils/AgeCalculator.java
  src/main/java/com/dduru/gildongmu/auth/utils/GoogleUserInfoExtractor.java
  src/main/java/com/dduru/gildongmu/auth/utils/OauthConstants.java
  src/main/java/com/dduru/gildongmu/auth/utils/OauthResponseUtils.java
  src/main/java/com/dduru/gildongmu/auth/utils/UrlParamBuilder.java
  src/main/java/com/dduru/gildongmu/common/exception/ErrorCode.java
  src/main/java/com/dduru/gildongmu/post/controller/PostController.java
  src/main/resources/data.sql
Labels: ✨ feature, BE

#47 feat: 안드로이드 클라이언트 Id 추가
  src/main/java/com/dduru/gildongmu/auth/service/GoogleLoginService.java
  src/main/resources/application-dev.yml
  src/test/resources/application-test.yml
Labels: ✨ feature, BE

#49 feat: prod.yml 수정 및 welcomepage 제작
  docker-compose.yml
  src/main/java/com/dduru/gildongmu/config/SecurityConfig.java
  src/main/java/com/dduru/gildongmu/home/controller/HomeController.java
  src/main/resources/application-prod.yml
Labels: 🔧 BE, 🌐 deploy

#59 feat: 개발환경 통일화 및 배포 설정 개선
  .github/workflows/ci.yml
  README.Docker.md
  build.gradle
  docker-compose.dev.yml
  docker-compose.yml
  src/main/java/com/dduru/gildongmu/home/controller/HomeController.java
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
  src/test/resources/application-test.yml
Labels: 🔧 BE, 🌐 deploy

#57 feat: 리프레시 토큰 + Redis 작업
  .github/workflows/ci.yml
  build.gradle
  docker-compose.dev.yml
  docker-compose.yml
  src/main/java/com/dduru/gildongmu/auth/controller/OauthController.java
  src/main/java/com/dduru/gildongmu/auth/dto/LoginResponse.java
  src/main/java/com/dduru/gildongmu/auth/dto/OauthUserInfo.java
  src/main/java/com/dduru/gildongmu/auth/dto/google/GoogleTokenResponse.java
  src/main/java/com/dduru/gildongmu/auth/dto/google/GoogleUserResponse.java
  src/main/java/com/dduru/gildongmu/auth/dto/kakao/KakaoAccount.java
  src/main/java/com/dduru/gildongmu/auth/dto/kakao/KakaoProfile.java
  src/main/java/com/dduru/gildongmu/auth/dto/kakao/KakaoTokenResponse.java
  src/main/java/com/dduru/gildongmu/auth/dto/kakao/KakaoUserResponse.java
  src/main/java/com/dduru/gildongmu/auth/exception/RefreshTokenException.java
  src/main/java/com/dduru/gildongmu/auth/exception/TokenRefreshFailedException.java
  src/main/java/com/dduru/gildongmu/auth/service/OauthAuthService.java
  src/main/java/com/dduru/gildongmu/auth/service/RefreshTokenService.java
  src/main/java/com/dduru/gildongmu/common/exception/ErrorCode.java
  src/main/java/com/dduru/gildongmu/common/exception/GlobalExceptionHandler.java
  src/main/java/com/dduru/gildongmu/common/jwt/JwtTokenProvider.java
  src/main/java/com/dduru/gildongmu/config/RedisConfig.java
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
  src/test/resources/application-test.yml
Labels: ✨ feature, 🔧 BE

#55 feat: 동행 모집글 상세 조회
  src/main/java/com/dduru/gildongmu/post/controller/PostController.java
  src/main/java/com/dduru/gildongmu/post/domain/Post.java
  src/main/java/com/dduru/gildongmu/post/dto/PostCreateRequest.java
  src/main/java/com/dduru/gildongmu/post/dto/PostDetailResponse.java
  src/main/java/com/dduru/gildongmu/post/dto/PostListRequest.java
  src/main/java/com/dduru/gildongmu/post/dto/PostSummaryResponse.java
  src/main/java/com/dduru/gildongmu/post/repository/PostRepositoryCustom.java
  src/main/java/com/dduru/gildongmu/post/repository/PostRepositoryImpl.java
  src/main/java/com/dduru/gildongmu/post/service/PostQueryService.java
  src/main/java/com/dduru/gildongmu/post/service/PostService.java
  src/main/resources/application-dev.yml
Labels: ✨ feature, 🔧 BE

#63 feat: 닉네임 추가 및 수정
  src/main/java/com/dduru/gildongmu/auth/controller/OauthController.java
  src/main/java/com/dduru/gildongmu/auth/dto/LoginResponse.java
  src/main/java/com/dduru/gildongmu/auth/service/OauthAuthService.java
  src/main/java/com/dduru/gildongmu/post/dto/PostDetailResponse.java
  src/main/java/com/dduru/gildongmu/user/controller/UserController.java
  src/main/java/com/dduru/gildongmu/user/domain/User.java
  src/main/java/com/dduru/gildongmu/user/dto/UserInfo.java
  src/main/java/com/dduru/gildongmu/user/dto/UserUpdateNicknameRequest.java
  src/main/java/com/dduru/gildongmu/user/service/UserService.java
Labels: ✨ feature, 🔧 BE

#66 feat: 로그아웃 구현
  build.gradle
  src/main/java/com/dduru/gildongmu/auth/controller/OauthController.java
  src/main/java/com/dduru/gildongmu/auth/dto/RefreshTokenRequest.java
  src/main/java/com/dduru/gildongmu/auth/service/OauthAuthService.java
  src/main/java/com/dduru/gildongmu/common/jwt/JwtAuthenticationFilter.java
  src/main/java/com/dduru/gildongmu/common/jwt/JwtTokenProvider.java
  src/main/java/com/dduru/gildongmu/config/SecurityConfig.java
  src/main/java/com/dduru/gildongmu/user/domain/User.java
Labels: ✨ feature, 🔧 BE

#68 feat: 모집글 참여 신청,승인,거절,취소 구현
  src/main/java/com/dduru/gildongmu/common/exception/ErrorCode.java
  src/main/java/com/dduru/gildongmu/participation/controller/ParticipationController.java
  src/main/java/com/dduru/gildongmu/participation/domain/Participation.java
  src/main/java/com/dduru/gildongmu/participation/dto/ParticipationRequest.java
  src/main/java/com/dduru/gildongmu/participation/dto/ParticipationResponse.java
  src/main/java/com/dduru/gildongmu/participation/enums/ParticipationStatus.java
  src/main/java/com/dduru/gildongmu/participation/exception/DuplicateParticipationException.java
  src/main/java/com/dduru/gildongmu/participation/exception/ParticipationNotFoundException.java
  src/main/java/com/dduru/gildongmu/participation/exception/RecruitmentClosedException.java
  src/main/java/com/dduru/gildongmu/participation/exception/SelfParticipationNotAllowedException.java
  src/main/java/com/dduru/gildongmu/participation/repository/ParticipationRepository.java
  src/main/java/com/dduru/gildongmu/participation/service/ParticipationService.java
  src/main/java/com/dduru/gildongmu/post/controller/PostController.java
  src/main/java/com/dduru/gildongmu/post/domain/Post.java
  src/main/java/com/dduru/gildongmu/post/exception/RecruitCountBelowZeroException.java
  src/main/java/com/dduru/gildongmu/post/exception/RecruitCountExceedCapacityException.java
  src/main/java/com/dduru/gildongmu/post/service/PostService.java
Labels: ✨ feature, 🔧 BE

#70 refactor: 도메인별 에러 처리를 정적 메서드로 통합
  docker-compose.dev.yml
  src/main/java/com/dduru/gildongmu/auth/exception/UserNotFoundException.java
  src/main/java/com/dduru/gildongmu/destination/repository/DestinationRepository.java
  src/main/java/com/dduru/gildongmu/participation/repository/ParticipationRepository.java
  src/main/java/com/dduru/gildongmu/participation/service/ParticipationService.java
  src/main/java/com/dduru/gildongmu/post/controller/PostController.java
  src/main/java/com/dduru/gildongmu/post/exception/DestinationNotFoundException.java
  src/main/java/com/dduru/gildongmu/post/exception/InvalidAgeRangeException.java
  src/main/java/com/dduru/gildongmu/post/exception/InvalidPostDateException.java
  src/main/java/com/dduru/gildongmu/post/exception/InvalidRecruitCapacityException.java
  src/main/java/com/dduru/gildongmu/post/exception/PostAccessDeniedException.java
  src/main/java/com/dduru/gildongmu/post/exception/PostNotFoundException.java
  src/main/java/com/dduru/gildongmu/post/repository/PostRepository.java
  src/main/java/com/dduru/gildongmu/post/service/PostQueryService.java
  src/main/java/com/dduru/gildongmu/post/service/PostService.java
  src/main/java/com/dduru/gildongmu/user/repository/UserRepository.java
  src/main/java/com/dduru/gildongmu/user/service/UserService.java
  src/main/resources/application-dev.yml
Labels: ✨ feature

#76 refactor: Access, Refresh 토큰 모두 userId를 Long으로 반환 및 요청
  src/main/java/com/dduru/gildongmu/auth/controller/OauthController.java
  src/main/java/com/dduru/gildongmu/auth/service/OauthAuthService.java
  src/main/java/com/dduru/gildongmu/auth/service/RefreshTokenService.java
  src/main/java/com/dduru/gildongmu/common/jwt/JwtTokenProvider.java
Labels: 🔧 BE, 🖥️ task
